name: nginx-thrift

ports:
  - port: 8080
    targetPort: 8080

container:
  image: yg397/openresty-thrift
  imageVersion: xenial
  name: nginx-thrift
  ports: 
  - containerPort: 8080
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"
  
configMaps:
  - name: jaeger-config.json
    mountPath: /usr/local/openresty/nginx/jaeger-config.json
    value: jaeger-config

  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf 
    value: nginx
