apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-rate-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-rate-proxy
  template:
    metadata:
      labels:
        app: memcached-rate-proxy
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '11211', '--admin-port', '9000', '--default-addr', 'memcached-rate.dsb-hr.svc.cluster.local:11211', '--propagate=false', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'memcached-rate']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 11211
            - name: admin
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: memcached-rate-proxy
spec:
  type: NodePort
  selector:
    app: memcached-rate-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 11211
      targetPort: 11211
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
