apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: consul
  name: consul
  namespace: hotel-res
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: consul
  strategy: {}
  template:
    metadata:
      name: consul
      labels:
        death-star-project: hotel-res
        app-name: consul
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: hashicorp/consul:latest
        name: consul
        ports:
        - containerPort: 8300
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 53
          protocol: UDP
        resources: {}
      restartPolicy: Always
status: {}
