apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: rate
  namespace: hotel-res
  name: rate
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: rate
  strategy: {}
  template:
    metadata:
      name: rate
      labels:
        death-star-project: hotel-res
        app-name: rate
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - command:
        - ./rate
        env:
        - name: DLOG
          value: DEBUG
        image: image-registry.openshift-image-registry.svc:5000/hotel-res/hotel_reserv_rate_single_node
        name: hotel-reserv-rate
        ports:
        - containerPort: 8084
        resources: {}
        volumeMounts:
        - mountPath: config.json
          subPath: config.json
          name: config-json
      restartPolicy: Always
      volumes:
      - name: config-json
        configMap:
          name: configmap-config-json
          items:
          - key: config.json
            path: config.json
status: {}
