---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-redis
  labels:
    death-star-project: social-network
    app: user-timeline-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: user-timeline-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-redis
  labels:
    death-star-project: social-network
    app: user-timeline-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-timeline-redis
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: user-timeline-redis
      name: user-timeline-redis
    spec:
      containers:
      - name: user-timeline-redis
        image: redis
      restartPolicy: Always
