apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Values.redis.primary.name }}-config
data:
 redis.conf: |-
    active-defrag-ignore-bytes 104857600
    shutdown-on-sigterm default
    proto-max-bulk-len 536870912
    propagation-error-behavior ignore
    cluster-migration-barrier 1
    activedefrag no
    cluster-replica-no-failover no
    # tls-client-key-file-pass ""
    tls-auth-clients yes
    # requirepass 
    replica-announce-port 0
    repl-backlog-size 1048576
    slave-lazy-flush no
    shutdown-on-sigint default
    acl-pubsub-default resetchannels
    active-defrag-threshold-upper 100
    busy-reply-threshold 5000
    unixsocketperm 0
    slave-ignore-maxmemory yes
    maxmemory-samples 5
    cluster-port 0
    cluster-slave-validity-factor 10
    replica-announced yes
    list-max-listpack-size -2
    # tls-key-file 
    databases 16
    rdb-save-incremental-fsync yes
    client-output-buffer-limit normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60
    repl-diskless-sync yes
    repl-diskless-load disabled
    cluster-allow-replica-migration yes
    # aof_rewrite_cpulist 
    # tls-ca-cert-file 
    hll-sparse-max-bytes 3000
    cluster-slave-no-failover no
    slave-serve-stale-data yes
    slave-read-only yes
    cluster-require-full-coverage yes
    hash-max-listpack-value 64
    appendonly no
    # unixsocket 
    # tls-ca-cert-dir 
    aof-disable-auto-gc no
    zset-max-listpack-entries 128
    stream-node-max-entries 100
    # tls-cert-file 
    # masterauth 
    supervised no
    oom-score-adj no
    active-expire-effort 1
    active-defrag-threshold-lower 10
    tcp-backlog 511
    dir /data
    tls-cluster no
    # tls-protocols 
    activerehashing yes
    replica-lazy-flush no
    cluster-announce-tls-port 0
    appenddirname appendonlydir
    replica-serve-stale-data yes
    repl-diskless-sync-delay 5
    save 3600 1 300 100 60 10000
    replica-ignore-disk-write-errors no
    # masteruser 
    min-replicas-to-write 0
    rdb-del-sync-files no
    always-show-logo no
    lazyfree-lazy-user-del no
    bind * -::*
    tcp-keepalive 300
    syslog-ident redis
    # pidfile 
    slave-announce-port 0
    # bio_cpulist 
    zset-max-listpack-value 64
    lfu-log-factor 10
    io-threads-do-reads no
    cluster-node-timeout 15000
    maxmemory 0
    list-max-ziplist-size -2
    tls-port 0
    dynamic-hz yes
    maxmemory-eviction-tenacity 10
    proc-title-template "{title} {listen-addr} {server-mode}"
    rdbchecksum yes
    tls-prefer-server-ciphers no
    disable-thp yes
    syslog-enabled no
    # slave-announce-ip 
    shutdown-timeout 10
    min-slaves-to-write 0
    active-defrag-cycle-max 25
    cluster-link-sendbuf-limit 0
    syslog-facility local0
    # bgsave_cpulist 
    replica-read-only yes
    list-compress-depth 0
    replica-ignore-maxmemory yes
    hz 10
    appendfsync everysec
    maxmemory-clients 0
    # logfile 
    active-defrag-max-scan-fields 1000
    zset-max-ziplist-entries 128
    # tls-ciphersuites 
    crash-memcheck-enabled yes
    lazyfree-lazy-expire no
    stop-writes-on-bgsave-error yes
    slave-priority 100
    latency-tracking-info-percentiles 50 99 99.9
    cluster-announce-bus-port 0
    slowlog-max-len 128
    repl-ping-slave-period 10
    tls-session-cache-size 20480
    repl-timeout 60
    # replicaof 
    acllog-max-len 128
    slowlog-log-slower-than 10000
    maxclients 10000
    sanitize-dump-payload no
    cluster-replica-validity-factor 10
    repl-ping-replica-period 10
    auto-aof-rewrite-percentage 100
    # aclfile 
    latency-monitor-threshold 0
    no-appendfsync-on-rewrite no
    aof-rewrite-incremental-fsync yes
    # slaveof 
    auto-aof-rewrite-min-size 67108864
    rdbcompression yes
    cluster-preferred-endpoint-type ip
    aof-use-rdb-preamble yes
    hash-max-ziplist-value 64
    # cluster-announce-ip 
    # tls-client-cert-file 
    # tls-client-key-file 
    oom-score-adj-values 0 200 800
    tls-session-cache-timeout 300
    appendfilename appendonly.aof
    replica-priority 100
    # tls-key-file-pass 
    aof-load-truncated yes
    enable-module-command no
    # tls-ciphers 
    lazyfree-lazy-server-del no
    repl-disable-tcp-nodelay no
    cluster-announce-port 0
    lazyfree-lazy-user-flush no
    min-replicas-max-lag 10
    loglevel notice
    socket-mark-id 0
    lua-time-limit 5000
    # notify-keyspace-events 
    cluster-config-file nodes.conf
    # bind-source-addr 
    enable-debug-command no
    lfu-decay-time 1
    repl-backlog-ttl 3600
    io-threads 1
    min-slaves-max-lag 10
    # cluster-announce-hostname 
    cluster-enabled no
    repl-diskless-sync-max-replicas 0
    hash-max-ziplist-entries 512
    client-query-buffer-limit 1073741824
    daemonize no
    port 6379
    set-proc-title yes
    aof-timestamp-enabled no
    jemalloc-bg-thread yes
    set-max-intset-entries 512
    stream-node-max-bytes 4096
    zset-max-ziplist-value 64
    maxmemory-policy noeviction
    # tls-dh-params-file 
    lazyfree-lazy-eviction no
    # ignore-warnings 
    hash-max-listpack-entries 512
    protected-mode no
    cluster-allow-reads-when-down no
    cluster-allow-pubsubshard-when-down yes
    tls-session-caching yes
    enable-protected-configs no
    tracking-table-max-keys 1000000
    # server_cpulist 
    latency-tracking yes
    dbfilename dump.rdb
    crash-log-enabled yes
    active-defrag-cycle-min 1
    timeout 0
    # replica-announce-ip 
    tls-replication no