apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-recommendation
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - command:
        - recommendation
        env:
        - name: DLOG
          value: DEBUG
        image: vhiveease/hotel_demo
        name: hotel-reserv-recommendation
        ports:
          - name: h2c
            containerPort: 8085
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
