apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-geo
spec:
  template:
    spec:
      containers:
      - command:
        - geo
        env:
        - name: DLOG
          value: DEBUG
        image: teresaliuchang/hotel_demo:v1.7
        name: hotel-reserv-geo
        ports:
          - name: h2c
            containerPort: 8083
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
