apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-profile
spec:
  template:
    spec:
      containers:
      - command:
        - profile
        env:
        - name: DLOG
          value: DEBUG
        image: vhiveease/hotel_demo
        name: hotel-reserv-profile
        ports:
          - name: h2c
            containerPort: 8081
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
