apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-proxy
  template:
    metadata:
      labels:
        app: recommendation-proxy
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '8085', '--admin-port', '9000', '--default-addr', 'recommendation.dsb-hr.svc.cluster.local:8085', '--propagate=true', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'recommendation']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 8085
            - name: admin
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-proxy
spec:
  type: NodePort
  selector:
    app: recommendation-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 8085
      targetPort: 8085
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
