name: profile

ports:
  - port: 8081
    targetPort: 8081
 
container:
  command: profile
  image: igorrudyk1/hotelreservation
  name: hotel-reserv-profile
  ports:
  - containerPort: 8081
  environments:
    logLevel: INFO
    jaegerSampleRatio: 1

configMaps:
  - name: service-config.json
    mountPath: /go/src/github.com/harlow/go-micro-services/config.json
    value: service-config
