    # depends_on:
    #   - write-home-timeline-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-service
  labels:
    death-star-project: social-network
    app-name: compose-post-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app-name: compose-post-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-service
  labels:
    death-star-project: social-network
    app-name: compose-post-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: compose-post-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: compose-post-service
      name: compose-post-service
    spec:
      containers:
      - name: compose-post-service
        image: yg397/social-network-microservices
        command: ["ComposePostService"]
      restartPolicy: Always
