apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-geo-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-geo-proxy
  template:
    metadata:
      labels:
        app: mongodb-geo-proxy
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '27017', '--admin-port', '9000', '--default-addr', 'mongodb-geo.dsb-hr.svc.cluster.local:27017', '--propagate=false', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'mongodb-geo']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 27017
            - name: admin
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-geo-proxy
spec:
  type: NodePort
  selector:
    app: mongodb-geo-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
