apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-proxy
  template:
    metadata:
      labels:
        app: user-proxy
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '8086', '--admin-port', '9000', '--default-addr', 'user.dsb-hr.svc.cluster.local:8086', '--propagate=true', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'user']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 8086
            - name: admin
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: user-proxy
spec:
  type: NodePort
  selector:
    app: user-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
