apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ingressgateway-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ingressgateway-main
  template:
    metadata:
      labels:
        app: frontend-ingressgateway-main
    spec:
      containers:
        - name: ingressgateway
          image: "ghcr.io/picop-rd/ingressgateway:latest"
          command: ['/bin/ingressgateway', '--port', '5000', '--env-id', 'main', '--destination', 'frontend-proxy.dsb-hr.svc.cluster.local:5000']
          imagePullPolicy: Always
          ports:
            - name: ingressgateway
              containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ingressgateway-main
spec:
  type: NodePort
  selector:
    app: frontend-ingressgateway-main
  ports:
    - name: ingressgateway
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
