version: '3'
services:
  seed:
    image: suu_project_repository/microservice_1:latest
    ports:
      - '1600:1600'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
  c1:
    image: suu_project_repository/microservice_2:latest
    ports:
      - '1601:1601'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: c1
      SEED_PORT_1600_TCP_ADDR: seed
  c2:
    image: suu_project_repository/microservice_1:latest # repeated first microservice, just as an example
    ports:
      - '1602:1602'
    environment:
      CLUSTER_PORT: 1602
      CLUSTER_IP: c2
      SEED_PORT_1600_TCP_ADDR: seed

