name: consul

replicas: 1

ports:
  - port: 8300
    targetPort: 8300
  - port: 8400
    targetPort: 8400
  - port: 8500
    targetPort: 8500
  - port: 8600
    protocol: UDP
    targetPort: 53

container:
  image: consul
  imageVersion: 1.13.2
  name: consul
  ports:
  - containerPort: 8300
  - containerPort: 8400
  - containerPort: 8500
  - containerPort: 53
    protocol: UDP
