apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-proxy
  template:
    metadata:
      labels:
        app: profile-proxy
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '8081', '--admin-port', '9000', '--default-addr', 'profile.dsb-hr.svc.cluster.local:8081', '--propagate=true', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'profile']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 8081
            - name: admin
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: profile-proxy
spec:
  type: NodePort
  selector:
    app: profile-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
