apiVersion: v1
kind: PersistentVolume
metadata:
  name: geo-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: geo-storage
  hostPath:
    path: /data/volumes/geo-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
