apiVersion: v1
kind: PersistentVolume
metadata:
  name: recommendation-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: recommendation-storage
  hostPath:
    path: /data/volumes/recommendation-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
