apiVersion: v1
kind: PersistentVolume
metadata:
  name: reservation-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: reservation-storage
  hostPath:
    path: /data/volumes/reservation-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
