name: frontend

ports:
  - port: 5000
    targetPort: 5000

container:
  command: frontend
  image: igorrudyk1/hotelreservation
  name: hotel-reserv-frontend
  ports:
  - containerPort: 5000

configMaps:
  - name: service-config.json
    mountPath: /go/src/github.com/harlow/go-micro-services/config.json
    value: service-config
