name: jaeger

replicas: 1

ports:
  - port: 14269
    targetPort: 14269
  - port: 5778
    targetPort: 5778
  - port: 14268
    targetPort: 14268
  - port: 14267
    targetPort: 14267
  - port: 16686
    targetPort: 16686
  - port: 5775
    protocol: UDP
    targetPort: 5775
  - port: 6831
    protocol: UDP
    targetPort: 6831
  - port: 6832
    protocol: UDP
    targetPort: 6832

container:
  image: jaegertracing/all-in-one
  imageVersion: 1.21.0
  name: hotel-reserv-jaeger
  ports:
  - containerPort: 14269
  - containerPort: 5778
  - containerPort: 14268
  - containerPort: 14267
  - containerPort: 16686
  - containerPort: 5775
    protocol: UDP
  - containerPort: 6831
    protocol: UDP
  - containerPort: 6832
    protocol: UDP
